[package]
name = "netwise"
version = "0.1.0"
authors = ["Nelson Sinis <nelsonsinis0@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.6.1"
ping = "0.5.2"
spinach = "2.1.0"
